### ISSUE TITLE
Error : UIView base class does not support pointerEvent value: box-none [Ask for help]

### ISSUE THREAD

**Issue by jihoon8730** [Abhinandan-Kushwaha/react-native-gifted-charts#491] opened 2024-01-09 01:32 UTC
**Describe the bug**
Error : UIView base class does not support pointerEvent value: box-none

**To Reproduce**

1. Enter a chart
2. click on the Pie chart
3. error

**Screenshots**
<img width="387" alt="image" src="https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/assets/88140865/1a5dab6d-85d8-4562-986b-e8abf1c663b8">

**My code**

**chartData**

```
const chartPercent = () => {
    const totalPortfolioValue = allPortfolioData.reduce(
      (total, item) => total + item.amount * item.crypto.price,
      0,
    );

    let colors = [
      'rgba(124, 225, 78, 1)',
      'rgba(23, 187, 239, 1)',
      'rgba(240, 183, 12, 1)',
      'rgba(224, 77, 115, 1)',
      'rgba(98, 98, 98, 1)',
    ];

    let colorsBlack = [
      'rgba(124, 225, 78, 0.3)',
      'rgba(23, 187, 239, 0.3)',
      'rgba(240, 183, 12, 0.3)',
      'rgba(224, 77, 115, 0.3)',
      'rgba(98, 98, 98, 0.3)',
    ];
    return allPortfolioData
      .map((item, index) => ({
        symbol: item.crypto.symbol,
        value: ((item.amount * item.crypto.price) / totalPortfolioValue) * 100,
        color:
          chartIndex === null
            ? colors[index]
            : index === chartIndex
            ? colors[index]
            : colorsBlack[index],
        focused: index === chartIndex,
      }))
      .sort((a, b) => b.value - a.value)
      .map((item, index) => ({
        ...item,
        color:
          chartIndex === null
            ? colors[index]
            : index === chartIndex
            ? colors[index]
            : colorsBlack[index],
      }));
  }
```
  
 **chartPie**

```
return (
    <PieChart
      data={pieData}
      donut
      strokeColor="#1B1C1E"
      strokeWidth={3}
      radius={85}
      innerRadius={70}
      sectionAutoFocus
      innerCircleColor={'#1B1C1E'}
      centerLabelComponent={renderCenterLabel}
    />
  )
```

 - Device: [iPhone14pro]
 - OS: [iOS16.4]

- react-native : "0.71.10",
- react-gifed-charts : "1.3.29",
- react-svg : "14.1.0"

**Additional context**
I tried updating the version in the GitHub issue, but it didn't work. Is this issue resolved? Or does anyone know how to fix it?

**Comment by Abhinandan-Kushwaha** [comment] 2024-01-09 07:49
Duplicate of https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/472

**Closed by Abhinandan-Kushwaha** 2024-01-09 07:49 UTC

**Comment by jihoon8730** [comment] 2024-01-09 08:47
@Abhinandan-Kushwaha 
Hi, there was a duplicate
Just one question, in #472 you mention the
changing the version to 1.3.28 seems to be the workaround, right? I don't like to mess around with version control.

**Comment by Abhinandan-Kushwaha** [comment] 2024-01-09 08:47
@jihoon8730 Are you facing this issue only on iOS or on both iOS and Android?

**Comment by jihoon8730** [comment] 2024-01-09 08:48
@Abhinandan-Kushwaha AOS could not determine

**Comment by jihoon8730** [comment] 2024-01-09 08:49
@Abhinandan-Kushwaha 
If downgrading to version 1.3.28 is a viable solution, let's try it!

**Comment by Abhinandan-Kushwaha** [comment] 2024-01-09 08:51
No, downgrading is not a solution. He was using `1.3.27` so I asked him to use the latest version at that time, that was `1.3.28`

**Comment by jihoon8730** [comment] 2024-01-09 08:52
@Abhinandan-Kushwaha 
Oh, I didn't see a good solution for the duplicate GitHub issue.

**Comment by Abhinandan-Kushwaha** [comment] 2024-01-09 08:59
Yes, I think I will have to release a new version with the fix.

Here's the problem-
`pointerEvents={'box-none'}` is not supported for `<Svg>` elements for older versions of react-native.

So, I am checking the react-native version. If it's higher than `0.70`, then I am using `pointerEvents={'box-none'}` otherwise I am using `pointerEvents={'auto}`

But, it seems like support for `box-none` started in version `0.72`, not `0.70` of react-native.
But I'm not sure about this. Once it is confirmed, I will change the condition form `>0.70` to `>0.72`

Give me a few minutes to confirm on this.

**Comment by jihoon8730** [comment] 2024-01-10 00:01
@Abhinandan-Kushwaha 

Glad to see this is something that can be supported though
Thanks and can you please leave a comment when you get a bug fix and version update?

**Comment by Abhinandan-Kushwaha** [comment] 2024-01-10 23:14
Hi @jihoon8730 👋
This has been fixed in version `1.3.30` and above.
Please use the latest version of the library.

**Comment by JobSoltero** [comment] 2024-02-15 18:44
Hi, I used version 1.4.7 of the library with RN 0.70.6 and I was not able focus any element while other element was already focused with touch events while using the Donut chart. I tried with all the possible configurations, the only one that worked was using controlled focus with focusOnPress disabled, but the focused element was not rendering.
I have tried with other releases:
-1.29.0, still the same problem
**-1.28.0 works**, but 1 out of 5 times it does not detect touch events

**Comment by PaoNapats** [comment] 2024-05-03 07:36
Hi, I used library version 1.4.9. RN version 0.72.4 and I still got this error "Error : UIView base class does not support pointerEvent value: box-none".  It happened when I was using PieChart. When I was using LineChart, it was working normally
