### ISSUE TITLE
Error while updating property 'd' of a view managed by rnsvgpath 

### ISSUE THREAD

**Issue by mehdinourollah** [Abhinandan-Kushwaha/react-native-gifted-charts#223] opened 2022-06-07 13:24 UTC
**Describe the bug**
Piechart crashes when all the values are 0 

**To Reproduce**

 `const data = [
        { value: 0 },
        { value: 0 }
    ]`
   
`<PieChart  data={data} />`

**Expected behavior**
It Shouldn't crash

**Screenshots**
![image](https://user-images.githubusercontent.com/5097056/172390765-7a7bbcd4-3414-439a-a072-d40a400d70f8.png)

 - Device: Samsung Galaxy A5
 - OS: Android
 - Version of the library being used is "react-native-gifted-charts": "^1.2.31"

**Additional context**
I am using a realtime data so the values may become 0 after all. I can handle it using conditional rendering for now but this issue is not ok because it causes crash in the app.

**Comment by Abhinandan-Kushwaha** [comment] 2022-06-09 11:47
Hi @mehdinourollah 👋
The issue is fixed in version `1.2.33`🎉

**Closed by Abhinandan-Kushwaha** 2022-06-09 11:47 UTC
