### ISSUE TITLE
Animated Bar Graphs not elevating upto its correct values in Android ( when isAnimated is set true )

### ISSUE THREAD

**Issue by Yash1026** [Abhinandan-Kushwaha/react-native-gifted-charts#311] opened 2023-04-08 06:52 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-gifted-charts@1.2.42` for the project I'm working on.

I was working on Animated bar graphs on iOS emulator and it worked fine, but when I used it in android emulator the bar graphs didn't raise to its actual value that it should and was raising in iOS correctly. Increasing the timeout duration to elevate fixed this issue that accounts for 400ms rather than 100ms. 
 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-gifted-charts/src/BarChart/Animated2DWithGradient.tsx b/node_modules/react-native-gifted-charts/src/BarChart/Animated2DWithGradient.tsx
index 9557d91..40dab23 100644
--- a/node_modules/react-native-gifted-charts/src/BarChart/Animated2DWithGradient.tsx
+++ b/node_modules/react-native-gifted-charts/src/BarChart/Animated2DWithGradient.tsx
@@ -84,7 +84,6 @@ const Animated2DWithGradient = (props: propTypes) => {
   const [initialRender, setInitialRender] = useState(
     noAnimation ? false : true,
   );
-
   useEffect(() => {
     if (!noAnimation) {
       if (initialRender) {
@@ -110,7 +109,7 @@ const Animated2DWithGradient = (props: propTypes) => {
       update: {type: 'linear', property: 'scaleXY'},
     });
     setInitialRender(false);
-    setTimeout(() => elevate(), Platform.OS == 'ios' ? 10 : 100);
+    setTimeout(() => elevate(), Platform.OS == 'ios' ? 10 : 400);
   };
 
   return (
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Abhinandan-Kushwaha** [comment] 2023-07-01 22:05
Hi @Yash1026 👋
Good to know that you were able to find the fix. I am unable to reproduce the issue. Instead when I change the timeout duration to 400, I can see a noticeable lag. 

Let's see if someone else reports the issue. Closing it until then.

**Closed by Abhinandan-Kushwaha** 2023-07-01 22:05 UTC
