### ISSUE TITLE
PointerComponent 

### ISSUE THREAD

**Issue by asifbadeghar54** [Abhinandan-Kushwaha/react-native-gifted-charts#195] opened 2022-05-20 12:37 UTC
Pointer Component in Ios Elevation and zIndex are not Working
![WhatsApp Image 2022-05-20 at 5 12 42 PM](https://user-images.githubusercontent.com/39403588/169529614-12f404bc-2136-4313-a841-b6b47125c20d.jpeg)

**Comment by Abhinandan-Kushwaha** [comment] 2022-05-20 21:57
Hi @asifbadeghar54 👋
The issue is now fixed in version `1.2.21`🎉

Now you don't need to use the zIndex property for the pointer component. By default the strip will appear behind the pointer component. If you want it otherwise, just set the property `stripOverPointer` to true inside the `pointerConfig` object.

**Closed by Abhinandan-Kushwaha** 2022-05-20 21:57 UTC

**Comment by asifbadeghar54** [comment] 2022-05-22 03:06
I have updated package but still iam facing same issue still the strip is over pointer component

**Comment by asifbadeghar54** [comment] 2022-05-22 03:09
> Hi @asifbadeghar54 👋 The issue is now fixed in version `1.2.21`🎉
> 
> Now you don't need to use the zIndex property for the pointer component. By default the strip will appear behind the pointer component. If you want it otherwise, just set the property `stripOverPointer` to true inside the `pointerConfig` object.

thank you so much now its fixed once again thanks for this wonderfull package

**Comment by asifbadeghar54** [comment] 2022-05-22 03:11
I have one more concern in Bar chart how to manage no of sections.

**Comment by Abhinandan-Kushwaha** [comment] 2022-05-22 08:29
Hi @asifbadeghar54 👋
Glad to know that you liked the library.

The no of sections can be managed with the `noOfSections` prop.
You can go through the [documentation](https://gifted-charts.web.app/barchart)
Also, [props list](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/blob/master/docs/BarChart/BarChartProps.md) can be useful to understand the library.
